export const options: string[] = [
  "All",
  "Alexa Skills",
  "Amazon Devices",
  "Amazon Fashion",
  "Amazon Fresh",
  "Amazon Fresh Meat",
  "Amazon Pharmacy",
  "Appliances",
  "Apps & Games",
  "Audible Audiobooks",
  "Baby",
  "Beauty",
  "Books",
  "Car & Motorbike",
  "Clothing & Accessories",
  "Collectibles",
  "Computers & Accessories",
  "Deals",
  "Electronics",
  "Furniture",
  "Garden & Outdoors",
  "Gift Cards",
  "Grocery & Gourmet Foods",
  "Health & Personal Care",
  "Home & Kitchen",
  "Industrial & Scientific",
  "Jewellery",
  "Kindle Store",
  "Luggage & Bags",
  "Luxury Beauty",
  "Movies & TV Shows",
  "MP3 Music",
  "Music",
  "Musical Instruments",
  "Office Products",
  "Pet Supplies",
  "Prime Video",
  "Shoes & Handbags",
  "Software",
  "Sports, Fitness & Outdoors",
  "Subscribe & Save",
  "Tools & Home Improvement",
  "Toys & Games",
  "Under ₹500",
  "Video Games",
  "Watches",
];

export const langOptions: string[] = [
  "EN",
  "हिन्दी - HI",
  "தமிழ் - TA",
  "తెలుగు - TE",
  "ಕನ್ನಡ - KN",
  "മലയാളം - ML",
  "বাংলা - BN",
  "मराठी - MR",
];
